"""initial schema

Revision ID: 68ffb6b8092b
Revises: 
Create Date: 2026-08-19 07:47:26.272715

"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '68ffb6b8092b'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dim_channel',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('sub_channel', sa.String(), nullable=False),
    sa.Column('channel', sa.String(), nullable=False),
    sa.Column('channel_group', sa.String(), nullable=False),
    sa.Column('valid_from', sa.Date(), nullable=False),
    sa.Column('valid_to', sa.Date(), nullable=True),
    sa.Column('is_current', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_dim_channel')),
    sa.UniqueConstraint('sub_channel', 'valid_from', name='uq_dim_channel_sub_channel_valid_from')
    )
    op.create_index('uq_dim_channel_sub_channel_current', 'dim_channel', ['sub_channel'], unique=True, postgresql_where=sa.text('is_current'))
    op.create_table('dim_product',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('node', sa.String(), nullable=False),
    sa.Column('product', sa.String(), nullable=False),
    sa.Column('product_group', sa.String(), nullable=False),
    sa.Column('valid_from', sa.Date(), nullable=False),
    sa.Column('valid_to', sa.Date(), nullable=True),
    sa.Column('is_current', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_dim_product')),
    sa.UniqueConstraint('node', 'valid_from', name='uq_dim_product_node_valid_from')
    )
    op.create_index('uq_dim_product_node_current', 'dim_product', ['node'], unique=True, postgresql_where=sa.text('is_current'))
    op.create_table('roles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_roles')),
    sa.UniqueConstraint('name', name='uq_roles_name')
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('display_name', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('email', name='uq_users_email')
    )
    op.create_table('approval',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('subject_type', sa.Enum('overlay', 'forecast_run', name='approval_subject_type'), nullable=False),
    sa.Column('subject_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'approved', 'rejected', name='approval_status'), server_default='pending', nullable=False),
    sa.Column('requested_by_user_id', sa.UUID(), nullable=False),
    sa.Column('requested_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('decided_by_user_id', sa.UUID(), nullable=True),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['decided_by_user_id'], ['users.id'], name=op.f('fk_approval_decided_by_user_id_users')),
    sa.ForeignKeyConstraint(['requested_by_user_id'], ['users.id'], name=op.f('fk_approval_requested_by_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_approval'))
    )
    op.create_table('audit_log',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('table_name', sa.String(), nullable=False),
    sa.Column('record_id', sa.String(), nullable=False),
    sa.Column('action', sa.Enum('insert', 'update', 'delete', name='audit_action'), nullable=False),
    sa.Column('actor_user_id', sa.UUID(), nullable=True),
    sa.Column('changed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('before', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('after', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], name=op.f('fk_audit_log_actor_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_log'))
    )
    op.create_table('forecast_run',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('label', sa.String(), nullable=True),
    sa.Column('kernel_version', sa.String(), nullable=False),
    sa.Column('book_snapshot_date', sa.Date(), nullable=False),
    sa.Column('period_grain', sa.Enum('week', 'month', name='period_grain'), nullable=False),
    sa.Column('random_seed', sa.BigInteger(), nullable=True),
    sa.Column('created_by_user_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], name=op.f('fk_forecast_run_created_by_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_forecast_run'))
    )
    op.create_table('user_role',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('granted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], name=op.f('fk_user_role_role_id_roles'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_role_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'role_id', name=op.f('pk_user_role'))
    )
    op.create_table('user_scope',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('product_group', sa.String(), nullable=True),
    sa.Column('channel_group', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], name=op.f('fk_user_scope_role_id_roles'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_scope_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_scope')),
    sa.UniqueConstraint('user_id', 'role_id', 'product_group', 'channel_group', name='uq_user_scope_grant')
    )
    op.create_table('forecast_value',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('run_id', sa.UUID(), nullable=False),
    sa.Column('node_id', sa.UUID(), nullable=False),
    sa.Column('channel_id', sa.UUID(), nullable=True),
    sa.Column('period', sa.Integer(), nullable=False),
    sa.Column('txn_type', sa.Enum('acquisition', 'regrade', 'churn', name='txn_type'), nullable=True),
    sa.Column('stage', sa.Enum('raised', 'closed', 'broken', 'book', 'base', name='forecast_stage'), nullable=False),
    sa.Column('model_value', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('overlay_value', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('final_value', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('p10', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('p50', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('p90', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['channel_id'], ['dim_channel.id'], name=op.f('fk_forecast_value_channel_id_dim_channel')),
    sa.ForeignKeyConstraint(['node_id'], ['dim_product.id'], name=op.f('fk_forecast_value_node_id_dim_product')),
    sa.ForeignKeyConstraint(['run_id'], ['forecast_run.id'], name=op.f('fk_forecast_value_run_id_forecast_run'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_forecast_value')),
    sa.UniqueConstraint('run_id', 'node_id', 'channel_id', 'period', 'txn_type', 'stage', name='uq_forecast_value_grain')
    )
    op.create_table('kernel_validation',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('run_id', sa.UUID(), nullable=True),
    sa.Column('node_id', sa.UUID(), nullable=False),
    sa.Column('channel_id', sa.UUID(), nullable=False),
    sa.Column('txn_type', sa.Enum('acquisition', 'regrade', 'churn', name='txn_type'), nullable=False),
    sa.Column('g', sa.ARRAY(sa.Numeric(precision=18, scale=9)), nullable=False),
    sa.Column('breakage', sa.Numeric(precision=18, scale=9), nullable=False),
    sa.Column('is_valid', sa.Boolean(), nullable=False),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('validated_by_user_id', sa.UUID(), nullable=True),
    sa.Column('validated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['channel_id'], ['dim_channel.id'], name=op.f('fk_kernel_validation_channel_id_dim_channel')),
    sa.ForeignKeyConstraint(['node_id'], ['dim_product.id'], name=op.f('fk_kernel_validation_node_id_dim_product')),
    sa.ForeignKeyConstraint(['run_id'], ['forecast_run.id'], name=op.f('fk_kernel_validation_run_id_forecast_run'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['validated_by_user_id'], ['users.id'], name=op.f('fk_kernel_validation_validated_by_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_kernel_validation'))
    )
    op.create_table('overlay',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('run_id', sa.UUID(), nullable=True),
    sa.Column('node_id', sa.UUID(), nullable=False),
    sa.Column('channel_id', sa.UUID(), nullable=True),
    sa.Column('period', sa.Integer(), nullable=False),
    sa.Column('txn_type', sa.Enum('acquisition', 'regrade', 'churn', name='txn_type'), nullable=True),
    sa.Column('stage', sa.Enum('raised', 'closed', 'broken', 'book', 'base', name='forecast_stage'), nullable=False),
    sa.Column('overlay_type', sa.Enum('migration_acq', 'migration_churn', 'manual_adjustment', name='overlay_type'), nullable=False),
    sa.Column('delta_value', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('created_by_user_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['channel_id'], ['dim_channel.id'], name=op.f('fk_overlay_channel_id_dim_channel')),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], name=op.f('fk_overlay_created_by_user_id_users')),
    sa.ForeignKeyConstraint(['node_id'], ['dim_product.id'], name=op.f('fk_overlay_node_id_dim_product')),
    sa.ForeignKeyConstraint(['run_id'], ['forecast_run.id'], name=op.f('fk_overlay_run_id_forecast_run'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_overlay'))
    )
    op.create_table('adjustment_log',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('forecast_value_id', sa.UUID(), nullable=False),
    sa.Column('previous_value', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('new_value', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('adjusted_by_user_id', sa.UUID(), nullable=True),
    sa.Column('adjusted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['adjusted_by_user_id'], ['users.id'], name=op.f('fk_adjustment_log_adjusted_by_user_id_users')),
    sa.ForeignKeyConstraint(['forecast_value_id'], ['forecast_value.id'], name=op.f('fk_adjustment_log_forecast_value_id_forecast_value'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_adjustment_log'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('adjustment_log')
    op.drop_table('overlay')
    op.drop_table('kernel_validation')
    op.drop_table('forecast_value')
    op.drop_table('user_scope')
    op.drop_table('user_role')
    op.drop_table('forecast_run')
    op.drop_table('audit_log')
    op.drop_table('approval')
    op.drop_table('users')
    op.drop_table('roles')
    op.drop_index('uq_dim_product_node_current', table_name='dim_product', postgresql_where=sa.text('is_current'))
    op.drop_table('dim_product')
    op.drop_index('uq_dim_channel_sub_channel_current', table_name='dim_channel', postgresql_where=sa.text('is_current'))
    op.drop_table('dim_channel')
    # ### end Alembic commands ###

    # Alembic's autogenerated table drops don't drop the native enum types
    # they depended on -- do that explicitly so downgrade leaves no orphans.
    for enum_name in (
        "overlay_type",
        "approval_subject_type",
        "approval_status",
        "audit_action",
        "period_grain",
        "forecast_stage",
        "txn_type",
    ):
        op.execute(f"DROP TYPE {enum_name}")
